### ISSUE TITLE
Fill in Pre-2008 Years of NASS Crop Data

### ISSUE THREAD

**Issue by Spatiotemporal-Exposures-and-Toxicology** [Spatiotemporal-Exposures-and-Toxicology/PrestoGP_Pesticides#2]

**Comment by sigmafelix** [comment]
Pre-2008 data take 62.3 percent of the AZO measurement data:
```r
 2000  2001  2002  2003  2004  2005  2006  2007  2008  2009  2010  2011  2012 
0.073 0.075 0.090 0.068 0.069 0.089 0.085 0.074 0.066 0.050 0.043 0.056 0.043 
 2013  2014  2015  2016  2017  2018  2019  2020  2021  2022 
0.018 0.013 0.011 0.012 0.020 0.009 0.011 0.012 0.010 0.003 
```

If we use crop data from available states for pre-2008 years, HUCs need to be strictly selected (i.e., completely within) to use the summaries. For other states, 2008 values can be filled.

**Comment by sigmafelix** [comment]
The proportion of each NASS crop class by HUC-8, -10, and -12 is summarized as below: each red line represents the median proportion of a crop class across all HUC-8, -10, and -12 areas in HUC-2. As we are interested in the temporal trend of the proportions, I did not include legends in each plot (Also, I think that legends of 130 classes would not be effective for communication).

#### HUC-8
![plot](https://github.com/Spatiotemporal-Exposures-and-Toxicology/PrestoGP_Pesticides/assets/25448786/bcabfeb3-790a-4b4f-b0a0-f8c0925038a5)

#### HUC-10
![plot](https://github.com/Spatiotemporal-Exposures-and-Toxicology/PrestoGP_Pesticides/assets/25448786/9b5a4f4a-f758-45d4-8d3f-3a070d8bd49b)


#### HUC-12
![plot](https://github.com/Spatiotemporal-Exposures-and-Toxicology/PrestoGP_Pesticides/assets/25448786/1a550f2e-fcb1-4fb1-8d73-941268ba2233)



Lines are generally parallel with exceptions of the crossing of two crop types (e.g., HUC-2 "12" area) and the switch from one to another (e.g., HUC-2 "01" area). We can try backcasting the proportions with splines or ARIMA to fill in pre-2008 values.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@sigmafelix  Thanks - this is very helpful. It looks like good evidence to marginalize away time. Would you agree?

**Comment by sigmafelix** [comment]
@Spatiotemporal-Exposures-and-Toxicology Yes, the maximum change was around 0.2 (20 percent) in HUC-2 06 and 10 areas, which would not be a big issue as the change is monotonic. I will take averages for the NASS variables then join them into the covariate data frame.

**Comment by sigmafelix** [comment]
We decided to take temporally marginal values. I reflected this on the covariate data, and will upload it after finishing to add the remaining covariates (TWI and agricultural pesticide usage).
